version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    volumes:
      - ./client/:/app
      # Error: EACCES: permission denied, mkdir '/app/node_modules/.vite/processing'
      # NOTE: https://stackoverflow.com/q/67087735
      - /app/node_modules/
    command: bash -c "chmod -R 777 /app/node_modules && npm run dev"
    environment:
      - PORT=4001
      - VITE_HOST=http://localhost:4000
    ports:
      - "4001:4001"
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    volumes:
      - ./server/:/app
    command: python -m uvicorn server.app:app --reload --host 0.0.0.0 --port 4002
    environment:
      - STATIC_INTERNAL_HOST=http://nginx:4000
      - STATIC_EXTERNAL_HOST=http://localhost:4000
    ports:
      - "4002:4002"
  nginx:
    image: nginx:stable
    volumes:
      - $BIRDCLEF_ROOT:/app/birdclef-2022/
      - ./nginx/birdclef-2022-listing.json:/app/birdclef-2022-listing.json
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # we're reverse proxying client and server, alongside serving static
      # content, so we need to ensure that these services are online
      - client
      - server
    ports:
      - "4000:4000"
