version: "3.8"

services:
  static:
    image: nginx:stable
    volumes:
      - $BIRDCLEF_ROOT:/app/birdclef-2022/
      - ./nginx/birdclef-2022-listing.json:/app/birdclef-2022-listing.json
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8001:8000"
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/app
      - /app/node_modules
    command: npm run dev
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "8000:8000"
    volumes:
      - ./server/:/app
    command: python -m uvicorn server.app:app --reload --host 0.0.0.0
    depends_on:
      - static
    environment:
      - STATIC_INTERNAL_HOST=http://static:8000
      - STATIC_EXTERNAL_HOST=http://localhost:8001
