version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/app
      - /app/node_modules
    command: npm run dev
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "8000:8000"
    volumes:
      - ./server/:/app
    command: uvicorn server.app:app --reload --host 0.0.0.0
