# docker-compose file for testing the cloudrun environment
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.cloudrun
    environment:
      # TODO: this needs to be configured in cloudrun
      - STATIC_EXTERNAL_HOST=http://localhost:8080
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
      - /app/app/node_modules/
      - /app/app/build/
      - /app/app/.svelte-kit/
