FROM python:3.10

WORKDIR /app
RUN pip install poetry
RUN poetry config virtualenvs.create false
COPY ../api/poetry.lock ../api/pyproject.toml ./
RUN poetry install --no-root

COPY ../api ./
RUN poetry install
CMD uvicorn api.app:app --reload
