FROM python:3.10

WORKDIR /app
RUN apt-get -y update && apt-get -y install libsndfile1-dev
RUN pip install poetry wheel
RUN poetry config virtualenvs.create false
COPY ../api/poetry.lock ../api/pyproject.toml ./
RUN poetry install --no-root

COPY ../api ./
RUN poetry install
CMD uvicorn api.app:app --reload
