FROM python:3.10

WORKDIR /app
RUN pip install poetry
RUN poetry config virtualenvs.create false
COPY ../server/poetry.lock ../server/pyproject.toml ./
RUN poetry install --no-root

COPY ../server ./
RUN poetry install
CMD uvicorn server.app:app --reload
